# brian's standard GitHub Actions macOS config for Perl 5 modules
# version 20220828.001
# https://github.com/briandfoy/github_workflows
# https://github.com/features/actions
# This file is licensed under the Artistic License 2.0
name: macos

on:
    push:
        branches:
            - '**'
            - '!**appveyor**'
            - '!**linux**'
            - '!**notest**'
            - '!**release**'
            - '!**windows**'
        tags-ignore:
            # I tag release pushes but those should have already been tested
            - 'release-*'
        paths-ignore:
            # list all the files which are irrelevant to the tests
            # non-code, support files, docs, etc
            - '.appveyor.yml'
            - '.gitattributes'
            - '.github/workflows/linux.yml'
            - '.github/workflows/release.yml'
            - '.github/workflows/windows.yml'
            - '.gitignore'
            - '.releaserc'
            - 'Changes'
            - 'LICENSE'
            - 'README.pod'
        pull_request:

jobs:
    perl:
        runs-on: macOS-latest
        steps:
            - uses: actions/checkout@v2
            - name: Platform check
              run: uname -a
            - name: Set up Perl
              run: |
                brew install perl
                ls -d /usr/local/Cellar/perl/*/bin | head -1 >> $GITHUB_PATH
                perl -v | perl -0777 -ne 'm/(v5\.\d+)/ && print "PERL_VERSION=$1"' >> $GITHUB_ENV
            - name: Perl version check
              run: perl -V
# cpan can operate with https, but we need IO::SSL::Socket, which
# does not come with Perl.
#
# When using cpan, use -M to specify the CDN-backed www.cpan.org
# mirror. I've noticed that letting CPAN.pm auto-choose mirrors
# sometimes selects things that the action can't reach.
#
# Also, use the -T option to not test the dependencies. Assume these
# mainline modules are good and save lots of CI minutes.
            - name: Prepare cpan
              run: |
                openssl version
                cpan -M http://www.cpan.org -T IO::Socket::SSL HTTP::Tiny
                cpan -M https://www.cpan.org -T ExtUtils::MakeMaker Test::Manifest
# Run author tests, but only if there's an xt/ directory
            - name: Author tests
              if: hashFiles('xt') != ''
              run: |
                cpan -M https://www.cpan.org -T Test::CPAN::Changes
                prove -r -b xt
# Running tests in parallel should be faster, but it's also more
# tricky in cases where different tests share a feature, such as a
# file they want to write to. Parallel tests can stomp on each other.
# Test in parallel to catch that, because other people will test your
# stuff in parallel.
            - name: Run tests in parallel
              run: |
                perl Makefile.PL
                HARNESS_OPTIONS=j10 make test
# The disttest target creates the distribution, unwraps it, changes
# into the dist dir, then runs the tests there. That checks that
# everything that should be in the dist is in the dist. If you forget
# to update MANIFEST with new modules, data files, and so on, you
# should notice the error.
            - name: Run distribution tests
              run: |
                perl Makefile.PL
                make disttest
                make clean
